#!/usr/bin/env python3
"""Write the FPGA testbench's stimulus/expected-output files.

Each output line is one inference, whitespace-separated decimal:

    shift  x0..x7  w00 w01 .. w73 (row-major, W[i][j])  b0..b3  y0..y3

Two suites per precision:

  golden    -- the frozen rows of verification/reference/vectors{,_int4}.csv
               exactly as committed (the same vectors the ASIC-side
               testbenches use), with each row re-checked against
               algorithm/reference_model.forward() before it is written so
               a stale CSV cannot silently pass.
  extended  -- more vectors from the same golden model: a seeded random
               sweep through algorithm/generate_vectors.generate() (so the
               distribution matches the golden set) plus directed corners
               (saturation, all-negative -> ReLU zero, shift=0 and large
               shifts, INT_MIN operands). Not committed; regenerated by
               `make vectors`.

Only the golden-model code in algorithm/ computes expected outputs; this
script never computes y itself.
"""

import argparse
import csv
import os
import sys

import numpy as np

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(REPO, "algorithm"))

from generate_vectors import (  # noqa: E402
    BIAS_RANGE_INT4,
    SHIFT,
    SHIFT_INT4,
    generate,
)
from reference_model import forward  # noqa: E402

REF_DIR = os.path.join(REPO, "verification", "reference")

CONFIG = {
    8: {"csv": "vectors.csv", "shift": SHIFT, "bias_range": 1000},
    4: {"csv": "vectors_int4.csv", "shift": SHIFT_INT4, "bias_range": BIAS_RANGE_INT4},
}

EXTENDED_SEED = 2026
EXTENDED_RANDOM = 1000


def fmt(shift, x, w, b, y):
    fields = [shift] + list(x) + list(np.asarray(w).flatten()) + list(b) + list(y)
    return " ".join(str(int(v)) for v in fields)


def golden(bits):
    cfg = CONFIG[bits]
    lines = []
    with open(os.path.join(REF_DIR, cfg["csv"])) as f:
        for row in csv.DictReader(f):
            x = np.array([int(row[f"x{i}"]) for i in range(8)], dtype=np.int8)
            w = np.array([[int(row[f"w{i}{j}"]) for j in range(4)] for i in range(8)],
                         dtype=np.int8)
            b = np.array([int(row[f"b{j}"]) for j in range(4)], dtype=np.int32)
            y_csv = [int(row[f"y{j}"]) for j in range(4)]
            _, y_model = forward(x, w, b, shift=cfg["shift"], bits=bits)
            if [int(v) for v in y_model] != y_csv:
                sys.exit(f"{cfg['csv']}: row disagrees with reference_model.forward() "
                         f"({y_csv} vs {list(y_model)}) -- regenerate the golden vectors")
            lines.append(fmt(cfg["shift"], x, w, b, y_csv))
    return lines


def corners(bits):
    qmin, qmax = -(2 ** (bits - 1)), 2 ** (bits - 1) - 1
    full = lambda v: np.full((8, 4), v, dtype=np.int8)  # noqa: E731
    vec = lambda v: np.full(8, v, dtype=np.int8)  # noqa: E731
    zero_b = np.zeros(4, dtype=np.int32)
    # Biases stay far below 2**30 so acc + rounding never overflows the
    # RTL's 32-bit signed adder; the Python model computes in int64 and
    # would not show that wrap.
    cases = [
        (vec(qmin), full(qmin), zero_b),                 # max positive product sum -> saturate
        (vec(qmin), full(qmax), zero_b),                 # most negative sum -> ReLU 0
        (vec(qmax), full(qmax), zero_b),
        (vec(0), full(0), np.array([0, 1, -1, 100000], dtype=np.int32)),  # bias only
        (np.arange(qmin, qmin + 8).astype(np.int8),
         np.arange(32).reshape(8, 4).astype(np.int8) % (qmax + 1),
         np.array([-5, 5, 1000, -1000], dtype=np.int32)),
    ]
    rng = np.random.default_rng(EXTENDED_SEED + bits)
    lines = []
    for x, w, b in cases:
        for shift in (0, 1, CONFIG[bits]["shift"], 15, 31):
            _, y = forward(x, w, b, shift=shift, bits=bits)
            lines.append(fmt(shift, x, w, b, y))
    # Random operands with a random shift per vector, so the requantize
    # shifter is exercised beyond the one fixed shift of the golden set.
    for _ in range(100):
        x = rng.integers(qmin, qmax + 1, size=8).astype(np.int8)
        w = rng.integers(qmin, qmax + 1, size=(8, 4)).astype(np.int8)
        b = rng.integers(-CONFIG[bits]["bias_range"], CONFIG[bits]["bias_range"],
                         size=4).astype(np.int32)
        shift = int(rng.integers(0, 32))
        _, y = forward(x, w, b, shift=shift, bits=bits)
        lines.append(fmt(shift, x, w, b, y))
    return lines


def extended(bits):
    cfg = CONFIG[bits]
    lines = [fmt(cfg["shift"], x, w, b, y)
             for x, w, b, _, y in generate(seed=EXTENDED_SEED, num_vectors=EXTENDED_RANDOM,
                                           shift=cfg["shift"], bits=bits,
                                           bias_range=cfg["bias_range"])]
    return lines + corners(bits)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--bits", type=int, choices=(4, 8), required=True)
    ap.add_argument("--suite", choices=("golden", "extended"), required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    lines = golden(args.bits) if args.suite == "golden" else extended(args.bits)
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {len(lines)} INT{args.bits} {args.suite} vectors -> {args.out}")


if __name__ == "__main__":
    main()
